# Generated by Django 3.1.1 on 2020-09-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telemetryid', models.CharField(max_length=255)),
                ('runtime', models.FloatField()),
                ('time', models.FloatField()),
                ('args', models.CharField(max_length=255)),
                ('kwargs', models.CharField(max_length=255)),
                ('runid', models.UUIDField()),
                ('pwd', models.TextField()),
                ('path', models.TextField()),
                ('executable', models.TextField()),
                ('ver', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
            ],
        ),
    ]
